package org.flp.model;
// Generated 2017.02.25. 10:13:28 by Hibernate Tools 4.3.1



/**
 * Blogcategory generated by hbm2java
 */
public class Blogcategory  implements java.io.Serializable {


     private Integer id;
     private String name;

    public Blogcategory() {
    }

    public Blogcategory(String name) {
       this.name = name;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


