package org.flp.model;
// Generated 2017.02.25. 10:13:28 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Blogentry generated by hbm2java
 */
public class Blogentry  implements java.io.Serializable {


     private Integer id;
     private String title;
     private String entry;
     private Date entrydate;
     private int blogcategoryId;

    public Blogentry() {
    }

    public Blogentry(String title, String entry, Date entrydate, int blogcategoryId) {
       this.title = title;
       this.entry = entry;
       this.entrydate = entrydate;
       this.blogcategoryId = blogcategoryId;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getEntry() {
        return this.entry;
    }
    
    public void setEntry(String entry) {
        this.entry = entry;
    }
    public Date getEntrydate() {
        return this.entrydate;
    }
    
    public void setEntrydate(Date entrydate) {
        this.entrydate = entrydate;
    }
    public int getBlogcategoryId() {
        return this.blogcategoryId;
    }
    
    public void setBlogcategoryId(int blogcategoryId) {
        this.blogcategoryId = blogcategoryId;
    }




}


